Configures all features for simulator
---
tags:
  - Configure Simulator

parameters:
  - in: body
    name: configure simulator
    required: true
    description: This body has modelling to simulator (project, resources, communication)
    schema:
      id: configure_simulator
      properties:

        project:
          type: string
          description: The project name
          example: Baby Monitor Project


        resources:
          type: object
          properties:
            Device:
              type: object
              properties:
                status:
                  type: array
                  items:
                    type: string
                senders:
                  type: array
                  items:
                    type: string
              example: {"Assistant":{"senders":[],"status":[]},"BabyMonitor":{"senders":[],"status":[]},"SmartLamp":{"senders":[],"status":["on","off"]},"SmartTV":{"senders":[],"status":["available","blocked"]},"Smartphone":{"senders":["BabyMonitor","SmartTV"],"status":[]}}
            

        communication:
          type: object
          properties:
            host:
              type: string
              description: hostname to conenction
              example: rabbitmq3:15672
            user:
              type: string
              description: username to connection
              example: guest
            password:
              type: string
              description: password to connection
              example: guest

responses:
  200:
    description: Returns a simple OK message