Configures all features for observer
---
tags:
  - Configure Observer

parameters:
  - in: body
    name: simulator modelling
    required: true
    description: This body has modelling to simulator (project, communication, scenarios)
    schema:
      id: configure_simulator
      properties:

        project:
          type: string
          description: The project name
          example: Baby Monitor Project


        communication:
          type: object
          properties:
            host:
              type: string
              description: hostname to conenction
              example: rabbitmq3:15672
            user:
              type: string
              description: username to connection
              example: guest
            password:
              type: string
              description: password to connection
              example: guest


        scenarios:
          type: object
          properties:
            normal:
              type: object
              properties:
                sender:
                  type: string
                  description: Sender of message
                  example: BabyMonitor
                "type":
                  type: string
                  description: Status of message
                  example: status
            adaptation:
              type: object
              properties:
                TVBlocked:
                  type: array
                  items:
                    type: object
                  example: [{"sender": "Smartphone", "type": "notification"}, {"sender": "SmartTV","type": "status","body": {"block": true}}]

responses:
  200:
    description: Returns a simple OK message